spring.application.name=karaoke
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
spring.datasource.username=springuser

# ここを半角・全角・空の順で試す
spring.datasource.password=p@ss

# スキーマとデータの初期化を有効にする
spring.sql.init.mode=always

logging.level.com.example.demo.karaoke.mapper=DEBUG
mybatis.configuration.map-underscore-to-camel-case=true
spring.jpa.defer-datasource-initialization=true
server.port=8080

# Hibernateの自動作成を「検証のみ」または「なし」にする
spring.jpa.hibernate.ddl-auto=none

